version: '3.8'
services:
  #########################
  #### MYSQL Container ####
  #########################
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  #########################
  #### Postgres Container #
  #########################
  postgresqlDB:
    container_name: postgresqlDB
    image: postgres:10.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  #########################
  #### Usuarios Container #
  #########################
  usuarioscontainer:
    container_name: usuarioscontainer
    #image: msvc_usuarios:latest
    image: drondon87/usuarios:latest
    ports:
      - '8001:8001'
    environment:
      PORT: 8001
      DB_HOST: mysqldb:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: 1234
      CURSOS_URL: cursoscontainer:8002/api/cursos
    networks:
      - spring
    depends_on:
      - mysqldb
    restart: always

  #########################
  #### Cursos Container ###
  #########################
  cursoscontainer:
    container_name: cursoscontainer
    #image: msvc_cursos:latest
    image: drondon87/cursos:latest
    ports:
      - '8002:8002'
    environment:
      PORT: 8002
      DB_HOST: postgresqlDB:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USUARIOS_URL: usuarioscontainer:8001/api/usuarios
    networks:
      - spring
    depends_on:
      - postgresqlDB
      - usuarioscontainer
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring