apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: mysqldb:3306
  database: msvc_usuarios
  curso_url: cursoscontainer:8002/api/cursos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgresqldb:5432
  database: msvc_cursos
  usuario_url: usuarioscontainer:8001/api/usuarios