apiVersion: apps/v1
kind: Deployment
metadata:
  name: cursoscontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cursoscontainer
  template:
    metadata:
      labels:
        app: cursoscontainer
    spec:
      containers:
        - image: drondon87/cursos:latest
          name: cursos
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: usuario_url