apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgresqldb
  name: postgresqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresqldb
  template:
    metadata:
      labels:
        app: postgresqldb
    spec:
      containers:
        - image: postgres:10.0
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc