apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresqldb
  name: postgresqldb
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresqldb
  type: ClusterIP